plugins {
    id 'org.jetbrains.kotlin.multiplatform'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.thisisthepy.compose'
}

kotlin {
    jvm('desktop') {}

    sourceSets {
        commonMain.dependencies {
            api "org.thisisthepy.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER"
            api "org.thisisthepy.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER"
            api "org.thisisthepy.compose.material:material:COMPOSE_VERSION_PLACEHOLDER"
            api "org.thisisthepy.compose.ui:ui-tooling:COMPOSE_VERSION_PLACEHOLDER"
        }
    }
}
