plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.compose"
    id "org.thisisthepy.compose"
}

kotlin {
    js(IR) {
        browser()
        binaries.executable()
    }
    wasm {
        browser()
        binaries.executable()
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation("org.thisisthepy.compose.ui:ui:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.material:material:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
            }
        }
    }
}

// test for https://github.com/JetBrains/compose-multiplatform/issues/3169
afterEvaluate {
    afterEvaluate {
        dependencies.add(kotlin.targets.js.compilations.main.compileDependencyConfigurationName, "org.jetbrains.kotlin:kotlin-stdlib")
    }
}