plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.compose"
    id "com.android.kotlin.multiplatform.library"
    id "org.thisisthepy.compose"
}

kotlin {
    android {
        namespace = "com.google.samples.apps.diceroller.shared"
        compileSdk {
            version = release(37) { minorApiLevel = 1 }
        }
    }

    jvm()

    sourceSets {
        getByName("commonMain") {
            dependencies {
                implementation("org.thisisthepy.compose.ui:ui:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.material3:material3:COMPOSE_MATERIAL3_VERSION_PLACEHOLDER")
            }
        }
    }
}
