#!/usr/bin/env bash
# Writes a definition for every skiko JNI entry point an image refers to and skiko does not
# implement on this platform.
#
# Usage: generate-foreign-stubs.sh <image linked with -undefined dynamic_lookup> <output.c>
#
# skiko declares every platform's native methods in its common sources: the X11 and Direct3D
# ones exist as declarations on macOS too. While Skia is a file opened at run time that is
# harmless, because a name is looked up when it is first called and another platform's never
# is. Linked into the image, every declared native method is a symbol the image refers to, and
# macOS binds them all at load, so the process dies on the first missing one before anything
# is drawn. They are still never called, so each is defined as a stop that says what it was.
set -euo pipefail
image="${1:?usage: $0 <image> <output.c>}"
output="${2:?usage: $0 <image> <output.c>}"
names="$(nm -u "$image" | sed 's/^_//' | grep -E '^Java_org_jetbrains_ski' | sort -u || true)"
{
    echo "/* Generated by generate-foreign-stubs.sh. Entry points of other platforms' graphics stacks. */"
    echo "#include <stdio.h>"
    echo "#include <stdlib.h>"
    echo ""
    echo "static void foreign_entry_point(const char *name) {"
    echo "    fprintf(stderr, \"%s belongs to another platform and was called on this one\\n\", name);"
    echo "    abort();"
    echo "}"
    for name in $names; do
        echo ""
        echo "void $name(void) { foreign_entry_point(\"$name\"); }"
    done
} > "$output"
echo "$(echo "$names" | grep -c . || true) stubs in $output"
