plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.thisisthepy.compose"
    id "org.jetbrains.kotlin.plugin.compose"
}

kotlin {
    js(IR) {
        browser()
    }
    jvm {}

    sourceSets {
        named("commonMain") {
        }
        named("jsMain") { 
            dependencies {
                implementation("org.jetbrains.compose.html:html-core:COMPOSE_UPSTREAM_VERSION_PLACEHOLDER")
                implementation("org.thisisthepy.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
            }
        }
        named("jvmMain") {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
    }
}
