plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.compose"
    id "org.thisisthepy.compose"
}

kotlin {
    js { browser() }

    sourceSets {
        commonMain.dependencies {
            api("org.thisisthepy.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
            api("org.thisisthepy.compose.ui:ui:COMPOSE_VERSION_PLACEHOLDER")
            api("org.thisisthepy.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER")
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("org.thisisthepy.compose.ui:ui-test:COMPOSE_VERSION_PLACEHOLDER")
        }
    }
}
